name: CI - Docker
on:
  push:
    branches: [ main2 ]
  workflow_dispatch:
  schedule:
    - cron: "45 * * * *"
jobs:
  Docker_Pull:
    runs-on: ubuntu-latest
    strategy:
       fail-fast: false
       matrix:
         runner: [0,1,2,3,4,5,6,7,8,9]
    steps:
      - uses: actions/checkout@v2
      - name: Docker
        run: |
          bash script_docker_pull.sh
          #seq 2 | parallel -n0 bash script_docker_pull.sh
  Docker_Pull_GHCR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker
        run: bash script_docker_pull_ghcr.sh
